baseurl: https://kodec.tech/
copyright: Made with ♥ | © Kode Crumbs 
title: Kode Crumbs
description: A student-led highschool computer club!
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        weight: 10
        url: /
      - identifier: joinus
        name: Join Us!
        weight: 20
        url: /joinus/
      - identifier: projects
        name: Projects
        weight: 30
        url: /projects/
      - identifier: faq
        name: FAQ
        weight: 40
        url: /faq/
      - identifier: team
        name: Team
        weight: 50
        url: /team/
      - identifier: search
        name: Search
        weight: 60
        url: /search/
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
module:
  imports:
  - path: github.com/willfaught/paige
  mounts:
  # Default mounts
  - source: "archetypes"
    target: "archetypes"
  - source: "assets"
    target: "assets"
  - source: "content"
    target: "content"
  - source: "data"
    target: "data"
  - source: "i18n"
    target: "i18n"
  - source: "layouts"
    target: "layouts"
  - source: "static"
    target: "static"
  # Bootstrap
  - source: "node_modules/bootstrap/dist/css"
    target: "assets/_paige/bootstrap"
    includeFiles: ["/bootstrap.css"]
  - source: "node_modules/bootstrap/dist/js"
    target: "assets/_paige/bootstrap"
    includeFiles: ["/bootstrap.bundle.js"]
  - source: "node_modules/bootstrap/js/dist"
    target: "static/_paige/bootstrap"
  - source: "node_modules/bootstrap/scss"
    target: "assets/_paige/bootstrap"
  # Bootstrap Icons
  - source: "node_modules/bootstrap-icons/font/fonts"
    target: "static/_paige/bootstrap-icons/fonts"
  - source: "node_modules/bootstrap-icons/font"
    target: "assets/_paige/bootstrap-icons"
    includeFiles: ["/bootstrap-icons.css"]  
outputs:
  home:
  - html
  - json
  - rss
params:
  authors:
    kartikey:
      name: "Kartikey Singh Chauhan"
    dhruv:
      name: "Dhruv Tandon"
    kunwar:
      name: "Kunwar Utkarsh"
    shreya:
      name: "Shreya Maurya"
taxonomies:
  author: "team"
paginate: 50
permalinks:
  team: /:year/:month/:day/:title/
  projects: /:year/:month/:day/:title/
timezone: Asia/Kolkata
titlecasestyle: Go
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 1
